services:
  webserver:
    build: .
    image: php:apache
    container_name: WEB_Server
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: DB_Server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hostapp
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: DB_Control
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mariadb

volumes:
  db_data: